---
title: "Code zur Masterarbeit"
author: "Xuan Son Le (4669361)"
date: "Abgabedatum: 10/10/2018"
output: pdf_document: keep_tex: true
editor_options: 
  chunk_output_type: console
---

```{r Setup, include=FALSE}
# Libraries importieren
knitr::opts_chunk$set(echo = TRUE)  
library(dplyr)
library(ggplot2)
library(xtable)
library(Hmisc)
library(params)
library(gridExtra)
library(caret)
library(caTools)
library(nnet)
library(e1071)
library(scales)
library(pROC)
options(xtable.floating = FALSE)
options(xtable.timestamp = "")
```

```{r Daten importieren, warning=FALSE}
# CSV-Dateien einlesen
censusDF <- read.csv('./Rohdaten/c.csv')[,-1] #Spalte 1 enthält nur Zeilennummer und wird entfernt
surveyDF <- read.csv('./Rohdaten/s.csv')[,-1] #Spalte 1 enthält nur Zeilennummer und wird entfernt

# Nur gemeinsame erklärende Variablen werden behalten
censusDF <- censusDF[,colnames(censusDF) %in% colnames(surveyDF)]
surveyDF <- data.frame("cuadrantes" = surveyDF[,"cuadrantes"],
                       surveyDF[,colnames(surveyDF) %in% colnames(censusDF)])
```

```{r Datenverständnis & -manipulation, warning = FALSE}
# Deskriptive Statistik
#describe(surveyDF)
#describe(censusDF)

# Anteil an fehlenden Werten bestimmen und in einer Tabelle zusammenfassen
missingSurvey <- data.frame("Variable" = colnames(surveyDF), "MissingSurvey" = t(data.frame(lapply(surveyDF, function(x) round(100*sum(is.na(x))/length(x),1)))), row.names = NULL)
missingCensus <- data.frame("Variable" = colnames(censusDF), "MissingCensus" = t(data.frame(lapply(censusDF, function(x) round(100*sum(is.na(x))/length(x),1)))), row.names = NULL)
missingRmVar <- left_join(missingSurvey, missingCensus, by = 'Variable')
missingAll <- left_join(missingSurvey, missingCensus, by = 'Variable')
missingRmVar <- missingRmVar[which(missingRmVar[,2] > 10 & missingRmVar[,3] > 10),]
row.names(missingRmVar) <- c(1:nrow(missingRmVar))

rm(missingSurvey)
rm(missingCensus)

# Latex-Tabelle-Formatierung 
#xtable(missingRmVar) 

# Variablen mit zu vielen fehlenden Werten in beiden Datensätzen werden entfernt
censusDF <- censusDF[, !(colnames(censusDF) %in% missingRmVar[1:5,1])]
surveyDF <- surveyDF[, !(colnames(surveyDF) %in% missingRmVar[1:5,1])]

# Hilfsvariablen werden entfernt
hilfsvariablen <- c('est_dis', 'ent', 'factor', 'idD', 'upm')
surveyDF <- surveyDF[ , !(names(surveyDF)  %in% hilfsvariablen)]
censusDF <- censusDF[ , !(names(censusDF)  %in% hilfsvariablen)]
rm(hilfsvariablen)

# parentesco wird entfernt, da die Faktoren nicht einheitlich zwischen surveyDF und censusDF
surveyDF <- surveyDF[ , !(names(surveyDF)  == "parentesco")]
censusDF <- censusDF[ , !(names(censusDF)  == "parentesco")]

# Variablen mit Near-Zero-Varianz
zeroVar <- data.frame(surveyDF = nearZeroVar(surveyDF, name = TRUE), 
                      censusDF = nearZeroVar(censusDF, name = TRUE))
# surveyDF <- surveyDF %>% select(-c(nearZeroVar(surveyDF)))
# censusDF <- censusDF %>% select(-c(nearZeroVar(censusDF)))

# Transformation numerischer in kategorialer Variablen. Ausgenommen sind edad und anos_escolaridad, da sie metrisch skaliert sind.
surveyDF$cuadrantes <- factor(surveyDF$cuadrantes, levels = c(1,2,3,4,5), 
                                 labels = c('extrem','moderat',
                                            'anfällig aufgrund Einkommen', 
                                            'anfällig aufgrund Sozialmangel', 'keine'))
listKlassen <- levels(surveyDF$cuadrantes)

surveyDF$asis_esc <- surveyDF$asis_esc - 1 #Damit gleiche Werte mit Census Datei
censusDF$sexo <- censusDF$sexo - 1 #Damit gleiche Werte mit Survey Datei

names(surveyDF)[6] <- 'anos_escolaridad' #Umbenennung für richtige Zeichencodierung
names(censusDF)[6] <- 'anos_escolaridad' #Umbenennung für richtige Zeichencodierung

listDF <- c("surveyDF", "censusDF")

for (i in c(1,2)) {
    
    df <- list(surveyDF, censusDF)[[i]]
    df$sexo <- factor(df$sexo, levels = c(0,1), labels = c('Weiblich','Männlich'))
    df$habl_ind <- factor(df$habl_ind, levels = c(0,1), labels = c('Nein','Ja'))
    df$asis_esc <- factor(df$asis_esc, levels = c(0,1), labels = c('Nein','Ja'))
    df$pea <- factor(df$pea)
    df$c_ocupa <- factor(df$c_ocupa)
    df$sector_act <- factor(df$sector_act)
    df$jub <- factor(df$jub, levels = c(0,1), labels = c('Nein','Ja'))
    df$dhind_cy <- factor(df$dhind_cy, levels = c(0,1), labels = c('Nein','Ja'))
    df$dhind_parent <- factor(df$dhind_parent, levels = c(0,1), labels = c('Nein','Ja'))
    df$ic_rezedu <- factor(df$ic_rezedu, levels = c(0,1), labels = c('Nein','Ja'))
    df$ic_asalud <- factor(df$ic_asalud, levels = c(0,1), labels = c('Nein','Ja'))
    df$ic_cv <- factor(df$ic_cv, levels = c(0,1), labels = c('Nein','Ja'))
    df$ic_sbv <- factor(df$ic_sbv, levels = c(0,1), labels = c('Nein','Ja'))
    df$rururb <- factor(df$rururb, levels = c(0,1), labels = c('Städtisch','Ländlich'))
    df$tam_loc <- factor(df$tam_loc, levels = c(1,2,3,4), labels = c('mehr als 100.000','15.000 bis 99.999', '2.500 bis 14.999', 'weniger als 2.500'))
    df$mun <- factor(df$mun)
    
    assign(listDF[i], df , envir = .GlobalEnv)
}

rm(df)
rm(listDF)
rm(i)

# idD als Zuordnungsvariable zur Kartenerstellung wird aus dem Trainingsmodell entfernt
surveyDF <- surveyDF[ , -which(names(surveyDF) == "mun")]
```

```{r Diagramme, warning = FALSE}
# Verteilung Armutskategorie 
abb61 <- ggplot(data = surveyDF, aes(x = cuadrantes, fill = cuadrantes)) +
    geom_bar(width = 0.75) +
    theme_light() +
    labs(y = "Anzahl der Beobachtung",
         x = "Armutskategorie") +
    scale_fill_discrete(guide = FALSE) +
    scale_x_discrete(labels = c("extreme\nArmut", "moderate\nArmut", 
                                "anfällige Armut\naufgrund\nniedrigem\nEinkommen",
                                "anfällige Armut\naufgrund\nSozialmangel", 
                                "keine\nArmut")) +
    theme(axis.line.x = element_line(color = "black", size = 0.5),
          axis.line.y = element_line(color = "black", size = 0.5),
          axis.text.x = element_text(size = 20, margin = margin(t = 5, r = 0, b = 10, l = 0)),
          axis.text.y = element_text(size = 20, margin = margin(t = 0, r = 0, b = 0, l = 10)),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 24, face = "bold"),
          axis.ticks.length = unit(.25, "cm"),
          axis.ticks = element_line(colour = "black"))

ggsave(plot = abb61, filename = "./Abbildungen/Abbildung_6_1.pdf", width = 297, height = 210, units = "mm")

# Armutskategorie nach Geschlecht
abb62 <- ggplot(data = surveyDF, aes(x = cuadrantes, fill = sexo)) +
    geom_bar(position = 'dodge', width = 0.75) +
    theme_light() +
    labs(y = "Anzahl der Beobachtung",
         x = " ",
         fill = "Geschlecht") +
    scale_x_discrete("Armutskategorie",
                     labels = c("extreme\nArmut", "moderate\nArmut", 
                                "anfällige Armut\naufgrund\nniedrigem\nEinkommen",
                                "anfällige Armut\naufgrund\nSozialmangel", 
                                "keine\nArmut")) +
    theme(axis.line.x = element_line(color = "black", size = 0.5),
          axis.line.y = element_line(color = "black", size = 0.5),
          axis.text.x = element_text(size = 20, margin = margin(t = 5, r = 0, b = 10, l = 0)),
          axis.text.y = element_text(size = 20, margin = margin(t = 0, r = 0, b = 0, l = 10)),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 24, face = "bold"),
          axis.ticks.length = unit(.25, "cm"),
          axis.ticks = element_line(colour = "black"),
          legend.text = element_text(size = 18),
          legend.title = element_text(size = 20, face = "bold"),
          legend.position = c(0.9,0.9),
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black"))

ggsave(plot = abb62, filename = "./Abbildungen/Abbildung_6_2.pdf", width = 297, height = 210, units = "mm")

# Armutskategorie nach Alter
abb63 <- ggplot(data = surveyDF, aes(x = edad, fill = cuadrantes)) +
    geom_histogram(position = "fill", bins = 30) +
    geom_vline(xintercept = mean(surveyDF$edad), linetype = "dashed", size = 1) +
    theme_light() +
    labs(y = "Anteil der Beobachtungen",
         x = "Alter",
         fill = "Armutskategorie") +
    scale_x_continuous(breaks = seq(0, 100, by = 10), expand = c(0,0)) +
    scale_y_continuous(expand = c(0,0)) +
    scale_fill_discrete("Armutskategorie",
                        breaks = c("1", "2", "3", "4", "5"), 
                        labels = c("extreme Armut\t", "moderate Armut\t", 
                                "anfällige Armut aufgrund niedrigem Einkommen",
                                "anfällige Armut aufgrund Sozialmangel", 
                                "keine Armut")) +
    theme(axis.line.x = element_line(color = "black", size = 0.5),
          axis.line.y = element_line(color = "black", size = 0.5),
          axis.text.x = element_text(size = 20, margin = margin(t = 5, r = 0, b = 10, l = 0)),
          axis.text.y = element_text(size = 20, margin = margin(t = 0, r = 0, b = 0, l = 10)),
          axis.title.x = element_text(size = 24, face = "bold"),
          axis.title.y = element_text(size = 24, face = "bold"),
          axis.ticks.length = unit(.25, "cm"),
          axis.ticks = element_line(colour = "black"),
          legend.title = element_blank(),
          legend.margin = margin(c(0,10,0,0)),
          legend.text = element_text(size = 18),
          legend.position = "bottom",
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black"),
          legend.box.margin = margin(c(5,0,5,0)),
          legend.key.width = unit(1.5,"line"),
          legend.key.height = unit(2,"line")) +
    guides(fill = guide_legend(nrow = 2))

ggsave(plot = abb63, filename = "./Abbildungen/Abbildung_6_3.pdf", width = 297, height = 210, units = "mm")

# Armutskategorie nach Bildungsjahre
abb64 <- ggplot(data = surveyDF, aes(x = anos_escolaridad, fill = cuadrantes)) +
    geom_histogram(stat = 'count', position = 'fill', na.rm = TRUE) +
    theme_light() +
    labs(y = "Anteil der Beobachtungen",
         x = "Bildungsjahre",
         fill = "Armutskategorie") + 
    scale_x_continuous(breaks = seq(min(surveyDF$anos_escolaridad, na.rm = TRUE), 
                                    max(surveyDF$anos_escolaridad, na.rm = TRUE), by = 1)) +
    scale_fill_discrete("Armutskategorie",
                        breaks = c("1", "2", "3", "4", "5"), 
                        labels = c("extreme Armut\t", "moderate Armut\t", 
                                "anfällige Armut aufgrund niedrigem Einkommen",
                                "anfällige Armut aufgrund Sozialmangel", 
                                "keine Armut")) +
    theme(axis.line.x = element_line(color = "black", size = 0.5),
          axis.line.y = element_line(color = "black", size = 0.5),
          axis.text.x = element_text(size = 20, margin = margin(t = 5, r = 0, b = 10, l = 0)),
          axis.text.y = element_text(size = 20, margin = margin(t = 0, r = 0, b = 0, l = 10)),
          axis.title.x = element_text(size = 24, face = "bold"),
          axis.title.y = element_text(size = 24, face = "bold"),
          axis.ticks.length = unit(.25, "cm"),
          axis.ticks = element_line(colour = "black"),
          legend.title = element_blank(),
          legend.margin = margin(c(0,10,0,0)),
          legend.text = element_text(size = 18),
          legend.position = "bottom",
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black"),
          legend.box.margin = margin(c(5,0,5,0)),
          legend.key.width = unit(1.5,"line"),
          legend.key.height = unit(2,"line"),
          strip.text = element_text(colour = "black", size = 16)) +
    guides(fill = guide_legend(nrow = 2)) +
    facet_grid(ic_rezedu ~ ., labeller = as_labeller(c('Nein' = 'Keine Verzögerung',
                                                       'Ja' = 'Mit Verzögerung'))) 

ggsave(plot = abb64, filename = "./Abbildungen/Abbildung_6_4.pdf", width = 297, height = 210, units = "mm")

# Armutskategorie nach Wohnort
abb65a <- ggplot(data = surveyDF, aes(x = rururb, fill = cuadrantes)) +
    geom_histogram(stat = 'count', position = 'fill') +
    theme_light() +
    labs(y = "Anteil der Beobachtung je Wohnort",
         x = " ") +
    scale_fill_discrete(labels = c("extreme Armut\t", "moderate Armut\t", 
                                "anfällige Armut aufgrund niedrigem Einkommen",
                                "anfällige Armut aufgrund Sozialmangel", 
                                "keine Armut")) +
    scale_y_continuous(labels = scales::percent_format()) +
    theme(axis.line.x = element_line(color = "black", size = 0.5),
          axis.line.y = element_line(color = "black", size = 0.5),
          axis.text.x = element_text(size = 20, margin = margin(t = 5, r = 0, b = 10, l = 0)),
          axis.text.y = element_text(size = 20, margin = margin(t = 0, r = 0, b = 0, l = 10)),
          axis.ticks.length = unit(.25, "cm"),
          axis.ticks = element_line(colour = "black"),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 24, face = "bold"),
          legend.title = element_blank(),
          legend.margin = margin(c(0,10,0,0)),
          legend.text = element_text(size = 18),
          legend.position = "bottom",
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black"),
          legend.box.margin = margin(c(5,0,5,0)),
          legend.key.width = unit(1.5,"line"),
          legend.key.height = unit(2,"line"),
          strip.text = element_text(colour = "black", size = 16)) +
    guides(fill = guide_legend(nrow = 2)) 

ggsave(plot = abb65a, filename = "./Abbildungen/Abbildung_6_5a.pdf", width = 297, height = 210, units = "mm")

# Armutskategorie nach Wohnortgröße
abb65b <- ggplot(data = surveyDF, aes(x = tam_loc, fill = cuadrantes)) +
    geom_histogram(stat = 'count', position = 'fill') +
    theme_light() +
    labs(y = "Anteil der Beobachtung je Wohnortgröße",
         x = " ") +
    scale_fill_discrete(labels = c("extreme Armut\t", "moderate Armut\t", 
                                "anfällige Armut aufgrund niedrigem Einkommen",
                                "anfällige Armut aufgrund Sozialmangel", 
                                "keine Armut")) +
    scale_x_discrete(limits = c("weniger als 2.500", "2.500 bis 14.999",
                                   "15.000 bis 99.999", "mehr als 100.000")) +
    scale_y_continuous(labels = scales::percent_format()) +
    theme(axis.line.x = element_line(color = "black", size = 0.5),
          axis.line.y = element_line(color = "black", size = 0.5),
          axis.text.x = element_text(size = 20, margin = margin(t = 5, r = 0, b = 10, l = 0)),
          axis.text.y = element_text(size = 20, margin = margin(t = 0, r = 0, b = 0, l = 10)),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 24, face = "bold"),
          axis.ticks.length = unit(.25, "cm"),
          axis.ticks = element_line(colour = "black"),
          legend.title = element_blank(),
          legend.margin = margin(c(0,10,0,0)),
          legend.text = element_text(size = 18),
          legend.position = "bottom",
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black"),
          legend.box.margin = margin(c(5,0,5,0)),
          legend.key.width = unit(1.5,"line"),
          legend.key.height = unit(2,"line"),
          strip.text = element_text(colour = "black", size = 16)) +
    guides(fill = guide_legend(nrow = 2)) +
    facet_grid(rururb ~ .)

ggsave(plot = abb65b, filename = "./Abbildungen/Abbildung_6_5b.pdf", width = 297, height = 210, units = "mm")
```

```{r Behandlung fehlender Werte, warning = FALSE}
# Fehlende Werte asis_esc & habl_ind 
## (surveyDF: Modus je Armutskategorie; censusDF: Modus)
Mode2 <- function(x) {tab <- table(x); names(tab)[which.max(tab)]} #Quelle: https://stat.ethz.ch/pipermail/r-help/2010-March/231975.html 
aggregate(surveyDF[c('asis_esc', 'habl_ind')],
          by = list(surveyDF$cuadrantes),
          FUN = Mode2)
rm(Mode2)

surveyDF$asis_esc[which(is.na(surveyDF$asis_esc))] <- 'Ja'
surveyDF$habl_ind[which(is.na(surveyDF$habl_ind))] <- 'Nein'

censusDF$asis_esc[which(is.na(surveyDF$asis_esc))] <- names(which.max(table(censusDF['asis_esc'])))
censusDF$habl_ind[which(is.na(surveyDF$habl_ind))] <- names(which.max(table(censusDF['habl_ind'])))

# Fehlende Werte anos_escolaridad 
# (surveyDF: Median je Armutskategorie; censusDF: Median)
anosCuad <- aggregate(surveyDF['anos_escolaridad'],
          by = list(surveyDF$cuadrantes),
          FUN = median,
          na.rm = TRUE,
          na.action = na.pass)
for (i in listKlassen) {
    
    surveyDF$anos_escolaridad[which(is.na(surveyDF$anos_escolaridad) &
                           surveyDF$cuadrantes == i)] <- anosCuad[which(anosCuad == i),2]
    
}

rm(i)
rm(anosCuad)

censusDF$anos_escolaridad[which(is.na(surveyDF$anos_escolaridad))] <- median(censusDF$anos_escolaridad, na.rm = TRUE)

# Restliche NAs werden aus censusDF entfernt
censusDF <- na.omit(censusDF)

# Kontrollieren, ob alle fehlenden Werte schon bereinigt wurden
all(!is.na(surveyDF))
all(!is.na(censusDF))
```

```{r Vorbereitung für Modellierung}
# Datensatz in Trainings- und Testdatendatz splitten
set.seed(111)
split = sample.split(surveyDF$cuadrantes, SplitRatio = 0.75)
surveyTrainDF = subset(surveyDF, split == TRUE)
surveyTestDF = subset(surveyDF, split == FALSE)
rm(split)

# Vorbereitung k-fache Kreuzvalidierung
# set.seed(111)
# folds <- createFolds(surveyDF$cuadrantes, k = 10, list = TRUE, returnTrain = FALSE)

# Transformiere die Zielvariable in Dummy-Variablen (in Testdaten)
dummyDF <- matrix(nrow = nrow(surveyTestDF), ncol = nlevels(surveyDF$cuadrantes))
colnames(dummyDF) <- listKlassen

for (i in listKlassen) {
    dummyDF[,i] <- as.numeric(surveyTestDF[1] == i)
}
```

```{r Modellierung Multimomiale logistische Regression}
# MLR mit Rückwärtselektion trainieren
MLR_Final <- multinom(cuadrantes ~ ., data = surveyTrainDF, maxit = 1000)
MLR_Final_AIC <- step(MLR_Final, direction = 'backward', trace = 0)

paste(MLR_Final$vcoefnames[which(!(MLR_Final$vcoefnames %in% MLR_Final_AIC$vcoefnames))], collapse = " ")

# MLR Vorhersage
MLR_yPred <- predict(MLR_Final_AIC, newdata = surveyTestDF[-1])

# MLR Vorhersage-Wahrscheinlichkeit
MLR_yProbPred <- predict(MLR_Final_AIC, newdata = surveyTestDF[-1], type = "probs")
all(as.numeric(MLR_yPred) == apply(MLR_yProbPred, 1, function(x) which.max(x)))

# MLR Confusion Matrix
MLR_ConfMat = table(true = surveyTestDF[,1], pred = MLR_yPred)
#xtable(MLR_ConfMat)

# MLR Genauigkeit
MLR_Accuracy <- round(sum(diag(MLR_ConfMat))/sum(MLR_ConfMat)*100,2)
```

```{r Modellierung Linear SVM}
# Parameteroptimierung linearer SVM
linSVM_Tune <- tune.svm(cuadrantes ~ ., data = surveyTrainDF, 
                        kernel = 'linear', cost = 10^c(-5:6))

linSVM_Tune_Result <- data.frame(C = linSVM_Tune$performances[,1], 
                                 Accuracy = 1 - linSVM_Tune$performances[,2])

# linSVM_Tune_Result <- read.csv("linSVM_Tune_Result.csv", sep = ",")[,-1]

# Plot tune-Ergebnisse linearer SVM
linSVM_tunePlot <- ggplot(linSVM_Tune_Result, aes(x = C, y = Accuracy)) +
    geom_line(size = 1.2) +
    theme_light() +
    labs(x = "C", y = "Genauigkeit") +
    scale_x_log10(breaks = 10^(-5:6),
                  labels = trans_format("log10", math_format(10^.x))) +
    scale_y_continuous(breaks = seq(round(min(linSVM_Tune_Result$Accuracy), 1),
                                    round(max(linSVM_Tune_Result$Accuracy), 1),
                                    0.05),
                       limits = c(min(linSVM_Tune_Result$Accuracy),
                                  round(max(linSVM_Tune_Result$Accuracy),1))) +
    theme(axis.line.x = element_line(color = "black", size = 0.5),
          axis.line.y = element_line(color = "black", size = 0.5),
          axis.text.x = element_text(size = 20, margin = margin(t = 5, r = 0, b = 10, l = 0)),
          axis.text.y = element_text(size = 20, margin = margin(t = 0, r = 0, b = 0, l = 10)),
          axis.title.x = element_text(size = 24, face = "bold"),
          #axis.title.x = element_blank(),
          axis.title.y = element_text(size = 24, face = "bold"),
          axis.ticks.length = unit(.25, "cm"),
          axis.ticks = element_line(colour = "black"))

ggsave(plot = linSVM_tunePlot, filename = "./Abbildungen/Abbildung_6_7_a.pdf", width = 297, height = 210, units = "mm")

# Trainiere linearer SVM
linSVM_Modell <- svm(cuadrantes ~ .,
              data = surveyTrainDF,
              type = "C-classification",
              kernel = "linear",
              cost = linSVM_Tune$best.parameters$cost,
              probability = TRUE) #C = 10^4

# Vorhersage linearer SVM
linSVM_yPred = predict(linSVM_Modell, newdata = surveyTestDF[-1])

# Vorhersage linearer SVM Wahrscheinlichkeiten
linSVM_yProbPred <- predict(linSVM_Modell, newdata = surveyTestDF[-1], probability=TRUE)
linSVM_yProbPred <- attr(linSVM_yProbPred, 'probabilities')
linSVM_yProbPred <- linSVM_yProbPred[,listKlassen]

# Confusion Matrix linearer SVM
linSVM_ConfMat <- table(true = surveyTestDF[,1], pred = linSVM_yPred)
#xtable(linSVM_ConfMat)

# Genauigkeit linearer SVM
linSVM_Accuracy <- round(sum(diag(linSVM_ConfMat))*100/sum(linSVM_ConfMat),2)
```

```{r Modellierung RBF SVM}
# Parameteroptimierung RBF SVM
RBFSVM_Tune <- tune.svm(cuadrantes ~ ., data = surveyTrainDF,
                 gamma = 10^(c(-4:2)), 
                 cost = 10^(c(-2:7)))

RBFSVM_Tune_Result <- data.frame(Gamma = RBFSVM_Tune$performances[,1],
                                 C = RBFSVM_Tune$performances[,2], 
                                 Accuracy = 1 - RBFSVM_Tune$performances[,3])

# Plot tune-Ergebnisse
RBFSVM_tunePlot <- ggplot(RBFSVM_Tune_Result, 
                          aes(x = Gamma, y = C)) +
    geom_tile(aes(fill = Accuracy), color = "white") +
    geom_text(aes(label = round(Accuracy,3)),
              size = 6) +
    scale_fill_gradient(low = "#F8766D", high = "#00BA38") +
    labs(x = "Gamma", y = "Cost") +
    scale_x_log10(breaks = 10^(-4:2),
                  labels = trans_format("log10", math_format(10^.x)),
                  expand = c(0,0)) +
    scale_y_log10(breaks = 10^(-2:7),
                  labels = trans_format("log10", math_format(10^.x)),
                  expand = c(0,0)) +
    theme(axis.line.x = element_line(color = "black", size = 0.5),
          axis.line.y = element_line(color = "black", size = 0.5),
          axis.text.x = element_text(size = 20, margin = margin(t = 5, r = 0, b = 10, l = 0)),
          axis.text.y = element_text(size = 20, margin = margin(t = 0, r = 5, b = 0, l = 0)),
          axis.title.x = element_text(size = 24, face = "bold"),
          axis.title.y = element_text(size = 24, face = "bold"),
          axis.ticks.length = unit(.25, "cm"),
          axis.ticks = element_line(colour = "black"))

RBFSVM_tunePlot

ggsave(plot = RBFSVM_tunePlot, filename = "./Abbildungen/Abbildung_6_7_b.pdf", width = 297, height = 210, units = "mm")

# Trainiere RBF SVM
RBFSVM_Modell <- svm(cuadrantes ~ .,
              data = surveyTrainDF,
              type = "C-classification",
              kernel = "radial", 
              gamma = RBFSVM_Tune$best.parameters$gamma, 
              cost = RBFSVM_Tune$best.parameters$cost,
              probability = TRUE)

# Vorhersage RBF SVM
RBFSVM_yPred = predict(RBFSVM_Modell, newdata = surveyTestDF[-1])

# Vorhersage RBF SVM
RBFSVM_yProbPred = predict(RBFSVM_Modell, newdata = surveyTestDF[-1], probability = TRUE)
RBFSVM_yProbPred <- attr(RBFSVM_yProbPred, 'probabilities')
RBFSVM_yProbPred <- RBFSVM_yProbPred[ , listKlassen] 

# Confusion Matrix RBF SVM
RBFSVM_ConfMat = table(true = surveyTestDF[,1], pred = RBFSVM_yPred)
#xtable(RBFSVM_ConfMat)

# Genauigkeit RBF SVM
RBFSVM_Accuracy <- round(sum(diag(RBFSVM_ConfMat))*100/sum(RBFSVM_ConfMat),2)
```

```{r Evaluation Mexiko-Daten}
# Erstellung von binären Konfusionsmatrixen
MLR_binConfMat <- list()
linSVM_binConfMat <- list()
RBFSVM_linConfMat <- list()

list_binConfMat <- c("MLR_binConfMat", "linSVM_binConfMat", "RBFSVM_linConfMat")
temp_df <- list()

for (j in c(1,2,3)) { #für jede binConfMat
    
    for (i in c("extrem", "moderat", "anfällig aufgrund Einkommen", "anfällig aufgrund Sozialmangel", "keine")) { #für jede Klasse
    
    df <- list(MLR_ConfMat, linSVM_ConfMat, RBFSVM_ConfMat)[[j]]
        
    temp <- c(df[i,i],
              sum(df[i,]) - df[i,i],
              sum(df[,i]) - df[i,i],
              sum(df) - sum(df[i,]) - sum(df[,i]) + df[i,i])
    
    temp_df[[i]] <- matrix(temp, nrow = 2, byrow = TRUE)
    
    rownames(temp_df[[i]]) <- c(i, "Rest")
    colnames(temp_df[[i]]) <- c(i, "Rest")
    
    
    }
    
    assign(list_binConfMat[j], temp_df , envir = .GlobalEnv)
}


# Erstellung ROC Kurven
MLR_ROC_1 <- roc(dummyDF[,1], MLR_yProbPred[,1])
MLR_ROC_2 <- roc(dummyDF[,2], MLR_yProbPred[,2])
MLR_ROC_3 <- roc(dummyDF[,3], MLR_yProbPred[,3])
MLR_ROC_4 <- roc(dummyDF[,4], MLR_yProbPred[,4])
MLR_ROC_5 <- roc(dummyDF[,5], MLR_yProbPred[,5])

linSVM_ROC_1 <- roc(dummyDF[,1], linSVM_yProbPred[,1])
linSVM_ROC_2 <- roc(dummyDF[,2], linSVM_yProbPred[,2])
linSVM_ROC_3 <- roc(dummyDF[,3], linSVM_yProbPred[,3])
linSVM_ROC_4 <- roc(dummyDF[,4], linSVM_yProbPred[,4])
linSVM_ROC_5 <- roc(dummyDF[,5], linSVM_yProbPred[,5])

RBFSVM_ROC_1 <- roc(dummyDF[,1], RBFSVM_yProbPred[,1])
RBFSVM_ROC_2 <- roc(dummyDF[,2], RBFSVM_yProbPred[,2])
RBFSVM_ROC_3 <- roc(dummyDF[,3], RBFSVM_yProbPred[,3])
RBFSVM_ROC_4 <- roc(dummyDF[,4], RBFSVM_yProbPred[,4])
RBFSVM_ROC_5 <- roc(dummyDF[,5], RBFSVM_yProbPred[,5])

MLR_ROC <- ggroc(list(MLR_ROC_1,MLR_ROC_2,MLR_ROC_3,MLR_ROC_4, MLR_ROC_5), size = 1.5, legacy.axes = TRUE) +
    theme_light() + geom_abline(slope=1, intercept=0, size = 1) +
    labs(y = "Richtig-Positiv-Rate",
         x = "Falsch-Positiv-Rate") + 
    scale_color_discrete("Armutskategorie",
                        breaks = c("1", "2", "3", "4", "5"), 
                        labels = c("extreme Armut\t", "moderate Armut\t", 
                                "anfällige Armut aufgrund niedrigem Einkommen",
                                "anfällige Armut aufgrund Sozialmangel", 
                                "keine Armut")) + 
    coord_fixed() +
    theme(axis.line.x = element_line(color = "black", size = 0.5),
          axis.line.y = element_line(color = "black", size = 0.5),
          axis.text.x = element_text(size = 20, margin = margin(t = 5, r = 0, b = 20, l = 0)),
          axis.text.y = element_text(size = 20, margin = margin(t = 0, r = 0, b = 0, l = 10)),
          axis.ticks.length = unit(.25, "cm"),
          axis.ticks = element_line(colour = "black"),
          axis.title.x = element_text(size = 24, face = "bold"),
          axis.title.y = element_text(size = 24, face = "bold"),
          legend.title = element_blank(),
          legend.margin = margin(c(0,10,0,0)),
          legend.text = element_text(size = 18),
          legend.position = "none",
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black"),
          legend.box.margin = margin(c(5,0,5,0)),
          legend.key.width = unit(1.5,"line"),
          legend.key.height = unit(2,"line"),
          strip.text = element_text(colour = "black", size = 16)) +
    guides(color = guide_legend(nrow = 2))

#ggsave(plot = MLR_ROC, filename = "./Abbildungen/Abbildung_6_8.pdf", width = 297, height = 210, units = "mm")

linSVM_ROC <- ggroc(list(linSVM_ROC_1,linSVM_ROC_2,linSVM_ROC_3,linSVM_ROC_4,linSVM_ROC_5), size = 1.5, legacy.axes = TRUE) +
    theme_light() + geom_abline(slope=1, intercept=0, size = 1) +
    labs(y = "Richtig-Positiv-Rate",
         x = "Falsch-Positiv-Rate") + 
    scale_color_discrete("Armutskategorie",
                        breaks = c("1", "2", "3", "4", "5"), 
                        labels = c("extreme Armut\t", "moderate Armut\t", 
                                "anfällige Armut aufgrund niedrigem Einkommen",
                                "anfällige Armut aufgrund Sozialmangel", 
                                "keine Armut")) + 
    coord_fixed() +
    theme(axis.line.x = element_line(color = "black", size = 0.5),
          axis.line.y = element_line(color = "black", size = 0.5),
          axis.text.x = element_text(size = 20, margin = margin(t = 5, r = 0, b = 20, l = 0)),
          axis.text.y = element_text(size = 20, margin = margin(t = 0, r = 0, b = 0, l = 10)),
          axis.ticks.length = unit(.25, "cm"),
          axis.ticks = element_line(colour = "black"),
          axis.title.x = element_text(size = 24, face = "bold"),
          axis.title.y = element_text(size = 24, face = "bold"),
          legend.title = element_blank(),
          legend.margin = margin(c(0,10,0,0)),
          legend.text = element_text(size = 18),
          legend.position = "none",
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black"),
          legend.box.margin = margin(c(5,0,5,0)),
          legend.key.width = unit(1.5,"line"),
          legend.key.height = unit(2,"line"),
          strip.text = element_text(colour = "black", size = 16)) +
    guides(color = guide_legend(nrow = 2))

#ggsave(plot = linSVM_ROC, filename = "./Abbildungen/Abbildung_6_8_b.pdf", width = 297, height = 210, units = "mm")


RBFSVM_ROC <- ggroc(list(RBFSVM_ROC_1,RBFSVM_ROC_2,RBFSVM_ROC_3,RBFSVM_ROC_4,RBFSVM_ROC_5), size = 1.5, legacy.axes = TRUE) +
    theme_light() + geom_abline(slope=1, intercept=0, size = 1) +
    labs(y = "Richtig-Positiv-Rate",
         x = "Falsch-Positiv-Rate") + 
    scale_color_discrete("Armutskategorie",
                        breaks = c("1", "2", "3", "4", "5"), 
                        labels = c("extreme Armut\t", "moderate Armut\t", 
                                "anfällige Armut aufgrund niedrigem Einkommen",
                                "anfällige Armut aufgrund Sozialmangel", 
                                "keine Armut")) + 
    coord_fixed() +
    theme(axis.line.x = element_line(color = "black", size = 0.5),
          axis.line.y = element_line(color = "black", size = 0.5),
          axis.text.x = element_text(size = 20, margin = margin(t = 5, r = 0, b = 20, l = 0)),
          axis.text.y = element_text(size = 20, margin = margin(t = 0, r = 0, b = 0, l = 10)),
          axis.ticks.length = unit(.25, "cm"),
          axis.ticks = element_line(colour = "black"),
          axis.title.x = element_text(size = 24, face = "bold"),
          axis.title.y = element_text(size = 24, face = "bold"),
          legend.title = element_blank(),
          legend.margin = margin(c(0,10,0,0)),
          legend.text = element_text(size = 18),
          legend.position = "bottom",
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black"),
          legend.box.margin = margin(c(5,0,5,0)),
          legend.key.width = unit(1.5,"line"),
          legend.key.height = unit(2,"line"),
          strip.text = element_text(colour = "black", size = 16)) +
    guides(color = guide_legend(nrow = 2))

ggsave(plot = RBFSVM_ROC, filename = "./Abbildungen/Abbildung_6_8_c.pdf", width = 297, height = 210, units = "mm")

```

```{Erstellung von Karten}
# Match Daten
load("./MEX_adm/matchFile.RData")
MLR_Karten <- predict(MLR_Final_AIC, newdata = censusDF)
censusDF$mun <- str_pad(censusDF$mun, 3, side = "left", pad = "0")
matchFile <- data.frame(matchFile[which(matchFile$nom_ent == "Guanajuato"),3:4])
matchFile$mun <- as.factor(as.character(matchFile$mun))
MLR_Karten <- data.frame(mun = censusDF$mun, pred = MLR_Karten)
MLR_Karten <- inner_join(MLR_Karten, matchFile, by = 'mun')

library(maptools)
library(stringr)
Karte <- readShapePoly("./MEX_adm/MEX_adm2.shp")
Karte <- Karte[Karte@data$NAME_1 == "Guanajuato", ]
plot(Karte)
Karte@data$ID_2

```

```{r Simulation Szenario 1}
# SVM Parameteroptimierung anhand einem Paar Sample - Population
trainDF <- popList[[1]]$smp
validDF <- popList[[1]]$pop

S1_linSVM_Tune <- tune.svm(y ~ X_1 + X_2, data = trainDF, kernel = 'linear',
             cost = 10^(c(-5:5)))

S1_RBFSVM_Tune <- tune.svm(y ~ X_1 + X_2, data = trainDF,
             gamma = 10^(c(-3:3)),
             cost = 10^(c(-3:3)))

# MLR und SVM für jedes Paar Sample - Population
S1_MLR_Accuracy <- data.frame(Fold = integer(), Accuracy = integer())
S1_linSVM_Accuracy <- data.frame(Fold = integer(), Accuracy = integer())
S1_RBFSVM_Accuracy <- data.frame(Fold = integer(), Accuracy = integer())

# S1_MLR_RmVar <- data.frame(Fold = integer(), rmVar = integer())
# S1_linSVM_RmVar <- data.frame(Fold = integer(), rmVar = integer())
# S1_RBFSVM_RmVar <- data.frame(Fold = integer(), rmVar = integer())

S1_MLR_ConfMat <- list()
S1_linSVM_ConfMat <- list()
S1_RBFSVM_ConfMat <- list()

for (i in c(1:simRuns)) {
    # Trainings- und Validierungsdaten
    trainDF <- popList[[i]]$smp # Sample als Trainingsdaten
    validDF <- popList[[i]]$pop # Population als Validierungsdaten
    
    # MLR Trainieren
    S1_MLR_FULL <- multinom(y ~ X_1 + X_2, data = trainDF)
    S1_MLR_AIC <- step(S1_MLR_FULL, direction = 'backward', trace = 0)
    # MLR Vorhersagen
    S1_MLR_yPred <- predict(S1_MLR_AIC, newdata = validDF[-1])
    # MLR Confusion Matrix
    S1_MLR_ConfMat = table(true = validDF[,1], pred = S1_MLR_yPred)
    # MLR Genauigkeit
    S1_MLR_Accuracy[i,] <- c(i, sum(diag(S1_MLR_ConfMat))/sum(S1_MLR_ConfMat))
    
    # linSVM Trainieren
    S1_linSVM_Modell <- svm(y ~ .,
                  data = trainDF,
                  type = "C-classification",
                  kernel = "radial",
                  cost = S1_linSVM_Tune$best.parameters$cost)
    # linSVM Vorhersage
    S1_linSVM_yPred = predict(S1_linSVM_Modell, newdata = validDF[-1])
    # linSVM Confusion Matrix
    S1_linSVM_ConfMat = table(true = validDF[,1], pred = S1_linSVM_yPred)
    # linSVM Genauigkeit
    S1_linSVM_Accuracy[i,] <- c(i,sum(diag(S1_linSVM_ConfMat))/sum(S1_linSVM_ConfMat))
    
    # RBFSVM Trainieren
    S1_RBFSVM_Modell <- svm(y ~ .,
                  data = trainDF,
                  type = "C-classification",
                  kernel = "radial",
                  gamma = S1_RBFSVM_Tune$best.parameters$gamma, 
                  cost = S1_RBFSVM_Tune$best.parameters$cost)
    # RBFSVM Vorhersage
    S1_RBFSVM_yPred = predict(S1_RBFSVM_Modell, newdata = validDF[-1])
    # RBFSVM Confusion Matrix
    S1_RBFSVM_ConfMat = table(true = validDF[,1], pred = S1_RBFSVM_yPred)
    # RBFSVM Genauigkeit
    S1_RBFSVM_Accuracy[i,] <- c(i,sum(diag(S1_RBFSVM_ConfMat))/sum(S1_RBFSVM_ConfMat))
   
}

S1_Accuracy <- data.frame(Accuracy = c(S1_MLR_Accuracy$Accuracy,
                                       S1_linSVM_Accuracy$Accuracy,
                                       S1_RBFSVM_Accuracy$Accuracy),
                          ID = c(rep("MLR", 100), 
                                 rep("linSVM", 100), 
                                 rep("RBFSVM", 100)))

abb610 <- ggplot(S1_Accuracy, aes(x = ID, y = Accuracy, color = ID)) + 
    geom_boxplot() +
    theme_light() +
    scale_x_discrete(limits = c('MLR', 'linSVM', 'RBFSVM')) +
    #scale_y_continuous(limits = c(min(S2_Accuracy$Accuracy), max(S2_Accuracy$Accuracy))) +
    scale_color_discrete(guide = FALSE) +
    theme(#plot.title = element_text(size = 28, face = "bold"),
          axis.line.x = element_line(color = "black", size = 0.5),
          axis.line.y = element_line(color = "black", size = 0.5),
          axis.text.x = element_text(size = 20, margin = margin(t = 5, r = 0, b = 10, l = 0)),
          axis.text.y = element_text(size = 20, margin = margin(t = 0, r = 0, b = 0, l = 10)),
          #axis.title.x = element_text(size = 24, face = "bold"),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 24, face = "bold"),
          axis.ticks.length = unit(.25, "cm"),
          axis.ticks = element_line(colour = "black"),
          legend.title = element_blank())

ggsave(plot = abb610, filename = "./Abbildungen/Abbildung_6_10.pdf", width = 297, height = 210, units = "mm")
```

```{r Simulation Szenario 2}
load("/Users/XuanSon/Desktop/complexSimData.Rdata")

# SVM Parameteroptimierung anhand einem Paar Sample - Population
trainDF <- popList[[1]]$smp
validDF <- popList[[1]]$pop

S2_linSVM_Tune <- tune.svm(y ~ . - intecept , data = trainDF, kernel = 'linear',
             cost = 10^(c(-3:3)))

S2_RBFSVM_Tune <- tune.svm(y ~ . - intecept, data = trainDF,
             gamma = 10^(c(-3:3)),
             cost = 10^(c(-3:3)))

# S2_polySVM_Tune <- tune.svm(y ~ . - intecept, data = trainDF, kernel = 'polynomial', 
#              gamma = 10^(c(-3:3)),
#              coef0 = 10^(c(1:3)),
#              degree = 2:5,
#              cost = 10^(c(-3:3))
#              )

S2_sigSVM_Tune <- tune.svm(y ~ . - intecept, data = trainDF, kernel = 'sigmoid',
             gamma = 10^(c(-5:3)),
             coef0 = 10^(c(-5:3)),
             cost = 10^(c(-3:3))
             )

# MLR und SVM für jedes Paar Sample - Population
S2_MLR_Accuracy <- data.frame(Fold = integer(), Accuracy = integer())
S2_linSVM_Accuracy <- data.frame(Fold = integer(), Accuracy = integer())
S2_RBFSVM_Accuracy <- data.frame(Fold = integer(), Accuracy = integer())
S2_sigSVM_Accuracy <- data.frame(Fold = integer(), Accuracy = integer())

# S1_MLR_RmVar <- data.frame(Fold = integer(), rmVar = integer())
# S1_linSVM_RmVar <- data.frame(Fold = integer(), rmVar = integer())
# S1_RBFSVM_RmVar <- data.frame(Fold = integer(), rmVar = integer())

S2_MLR_ConfMat <- list()
S2_linSVM_ConfMat <- list()
S2_RBFSVM_ConfMat <- list()
S2_sigSVM_ConfMat <- list()

for (i in c(1:200)) {
    # Trainings- und Validierungsdaten
    trainDF <- popList[[i]]$smp # Sample als Trainingsdaten
    validDF <- popList[[i]]$pop # Population als Validierungsdaten
    
    trainDF[,c('y', 'X_5', 'X_6')] <- lapply(trainDF[,c('y', 'X_5', 'X_6')],
                                             function(x) factor(x))
    validDF[,c('y', 'X_5', 'X_6')] <- lapply(validDF[,c('y', 'X_5', 'X_6')],
                                             function(x) factor(x))
    
    # MLR Trainieren
    S2_MLR_FULL <- multinom(y ~ . - intecept, data = trainDF)
    S2_MLR_AIC <- step(S2_MLR_FULL, direction = 'backward', trace = 0)
    # MLR Vorhersagen
    S2_MLR_yPred <- predict(S2_MLR_AIC, newdata = validDF[-1])
    # MLR Confusion Matrix
    S2_MLR_ConfMat = table(true = validDF[,1], pred = S2_MLR_yPred)
    # MLR Genauigkeit
    S2_MLR_Accuracy[i,] <- c(i, sum(diag(S2_MLR_ConfMat))/sum(S2_MLR_ConfMat))
    
    # linSVM Trainieren
    S2_linSVM_Modell <- svm(y ~ . - intecept,
                  data = trainDF,
                  type = "C-classification",
                  kernel = "radial",
                  cost = S2_linSVM_Tune$best.parameters$cost)
    # linSVM Vorhersage
    S2_linSVM_yPred = predict(S2_linSVM_Modell, newdata = validDF[-1])
    # linSVM Confusion Matrix
    S2_linSVM_ConfMat = table(true = validDF[,1], pred = S2_linSVM_yPred)
    # linSVM Genauigkeit
    S2_linSVM_Accuracy[i,] <- c(i,sum(diag(S2_linSVM_ConfMat))/sum(S2_linSVM_ConfMat))
    
    # RBFSVM Trainieren
    S2_RBFSVM_Modell <- svm(y ~ . - intecept,
                  data = trainDF,
                  type = "C-classification",
                  kernel = "radial",
                  gamma = S2_RBFSVM_Tune$best.parameters$gamma, 
                  cost = S2_RBFSVM_Tune$best.parameters$cost)
    # RBFSVM Vorhersage
    S2_RBFSVM_yPred = predict(S2_RBFSVM_Modell, newdata = validDF[-1])
    # RBFSVM Confusion Matrix
    S2_RBFSVM_ConfMat = table(true = validDF[,1], pred = S2_RBFSVM_yPred)
    # RBFSVM Genauigkeit
    S2_RBFSVM_Accuracy[i,] <- c(i,sum(diag(S2_RBFSVM_ConfMat))/sum(S2_RBFSVM_ConfMat))
   
    # sigSVM Trainieren
    S2_sigSVM_Modell <- svm(y ~ . - intecept,
                  data = trainDF,
                  type = "C-classification",
                  kernel = "sigmoid",
                  cost = S2_sigSVM_Tune$best.parameters$cost,
                  gamma = S2_sigSVM_Tune$best.parameters$gamma,
                  coef0 = S2_sigSVM_Tune$best.parameters$coef0)
    # sigSVM Vorhersage
    S2_sigSVM_yPred = predict(S2_sigSVM_Modell, newdata = validDF[-1])
    # sigSVM Confusion Matrix
    S2_sigSVM_ConfMat = table(true = validDF[,1], pred = S2_sigSVM_yPred)
    # sigSVM Genauigkeit
    S2_sigSVM_Accuracy[i,] <- c(i,sum(diag(S2_sigSVM_ConfMat))/sum(S2_sigSVM_ConfMat))
}

S2_Accuracy <- data.frame(Accuracy = c(S2_MLR_Accuracy$Accuracy,
                                       S2_linSVM_Accuracy$Accuracy,
                                       S2_RBFSVM_Accuracy$Accuracy,
                                       S2_sigSVM_Accuracy$Accuracy),
                          ID = c(rep("MLR", 200), 
                                 rep("linSVM", 200),
                                 rep("RBFSVM", 200),
                                 rep("sigSVM", 200)))

abb611 <- ggplot(S2_Accuracy, aes(x = ID, y = Accuracy, color = ID)) + 
    geom_boxplot() +
    theme_light() +
    scale_x_discrete(limits = c('MLR', 'linSVM', 'RBFSVM', 'sigSVM')) +
    #scale_y_continuous(limits = c(min(S2_Accuracy$Accuracy), max(S2_Accuracy$Accuracy))) +
    scale_color_discrete(guide = FALSE) +
    theme(#plot.title = element_text(size = 28, face = "bold"),
          axis.line.x = element_line(color = "black", size = 0.5),
          axis.line.y = element_line(color = "black", size = 0.5),
          axis.text.x = element_text(size = 20, margin = margin(t = 5, r = 0, b = 10, l = 0)),
          axis.text.y = element_text(size = 20, margin = margin(t = 0, r = 0, b = 0, l = 10)),
          #axis.title.x = element_text(size = 24, face = "bold"),
          axis.title.x = element_blank(),
          axis.title.y = element_text(size = 24, face = "bold"),
          axis.ticks.length = unit(.25, "cm"),
          axis.ticks = element_line(colour = "black"),
          legend.title = element_blank())

ggsave(plot = abb611, filename = "./Abbildungen/Abbildung_6_11a.pdf", width = 297, height = 210, units = "mm")

```





